Update re-run.yml

diff --git a/.github/workflows/re-run.yml b/.github/workflows/re-run.yml
--- a/.github/workflows/re-run.yml
+++ b/.github/workflows/re-run.yml
@@ -13,100 +13,99 @@ jobs:
         run: |
           echo "The Workflow Run ${{ github.event.workflow_run.name }} has failed! " >> $GITHUB_STEP_SUMMARY
           echo "View the failed run attempt (#${{ github.event.workflow_run.run_attempt }}) here: ${{ github.event.workflow_run.html_url }}" >> $GITHUB_STEP_SUMMARY
-          email="${{ github.event.workflow_run.head_commit.author.email }}"
-          username=$(echo "$email" | cut -d'@' -f1 | awk -F'+' '{print $2}')
-          echo "GitHub Username: $username"
           # echo '${{ toJSON(github) }}'
           # echo "Job ID: ${{ github.job }}"
           # echo "Current run: ${{ github.run_attempt }}"
           # echo "Author: ${{ github.event.workflow_run.head_commit.author.name }}"
           # echo "Actor: ${{ github.actor }}"
-      # - name: Rerun failed jobs in the current workflow
-      #   env:
-      #     GH_TOKEN: ${{ github.token }}
-      #   run: |
-      #     MAX_RUNS=2
-      #     CURRENT_RUN=${{ github.event.workflow_run.run_attempt }}
-      #     if [ $CURRENT_RUN -lt $MAX_RUNS ]; then
-      #       gh run rerun ${{ github.event.workflow_run.id }} --repo ${{ github.repository }} --failed
-      #     else
-      #       exit 1
-      #     fi
-      # - name: Check out the repo
-      #   if: ${{ !cancelled() && failure() }} # Run only if the previous step failed
-      #   uses: actions/checkout@v4
+      - name: Rerun failed jobs in the current workflow
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          MAX_RUNS=2
+          CURRENT_RUN=${{ github.event.workflow_run.run_attempt }}
+          if [ $CURRENT_RUN -lt $MAX_RUNS ]; then
+            gh run rerun ${{ github.event.workflow_run.id }} --repo ${{ github.repository }} --failed
+          else
+            exit 1
+          fi
+      - name: Check out the repo
+        if: ${{ !cancelled() && failure() }} # Run only if the previous step failed
+        uses: actions/checkout@v4
 
-      # - name: Get Short Commit
-      #   if: ${{ !cancelled() && failure() }} # Run only if the previous step failed
-      #   run: |
-      #     commit_short=$(git rev-parse --short ${{ github.event.workflow_run.head_sha }})
-      #     echo "BREAKING_COMMIT_SHORT=$commit_short" >> $GITHUB_ENV
-      #     echo "PR_AUTHOR=${{ github.event.workflow_run.head_commit.author.login/@/ }}" >> $GITHUB_ENV
+      - name: Get Short Commit
+        if: ${{ !cancelled() && failure() }} # Run only if the previous step failed
+        run: |
+          commit_short=$(git rev-parse --short ${{ github.event.workflow_run.head_sha }})
+          echo "BREAKING_COMMIT_SHORT=$commit_short" >> $GITHUB_ENV
+          email="${{ github.event.workflow_run.head_commit.author.email }}"
+          username=$(echo "$email" | cut -d'@' -f1 | awk -F'+' '{print $2}')
+          echo "PR_AUTHOR=$username" >> $GITHUB_ENV
   
-      # - name: Slack Notification
-      #   uses: ./.github/actions/slack-notification
-      #   if: ${{ !cancelled() && failure() }} # Run only if the previous step failed
-      #   env:
-      #     BREAKING_COMMIT: "${{ github.event.workflow_run.head_sha }}"
-      #     RUN_URL: "${{ github.event.workflow_run.html_url }}"
-      #     RUN_NAME: "${{ github.event.workflow_run.name }}"
-      #     BRANCH: "${{ github.event.workflow_run.head_branch }}"
-      #     REPO: "${{ github.repository }}"
-      #   with:
-      #     vault-url: ${{ secrets.VAULT_ADDR }}
-      #     vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
-      #     vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
-      #     slack-payload: |
-      #       {
-      #         "text": ":alert: CI is failing on ${{ github.event.workflow_run.head_branch }} :alert:",
-      #       	"blocks": [
-      #           {
-      #             "type": "header",
-      #             "text": {
-      #               "type": "plain_text",
-      #               "text": ":alert: CI is failing on ${{ github.event.workflow_run.head_branch }} :alert:",
-      #               "emoji": true
-      #             }
-      #           }
-      #         ],
-      #         "attachments": [
-      #           {
-      #             "color": "#D40E0D",
-      #             "blocks": [
-      #               {
-      #                 "type": "section",
-      #                 "text": {
-      #                   "type": "mrkdwn",
-      #                   "text": "Commit <https://github.com/elastic/cloudbeat/commit/${{env.BREAKING_COMMIT}}|${{env.BREAKING_COMMIT_SHORT}}> by ${{env.PR_AUTHOR}} has failing <${{env.RUN_URL}}|${{env.RUN_NAME}}> tests on the `${{env.BRANCH}}` branch."
-      #                 }
-      #               },
-      #               {
-      #                 "type": "divider"
-      #               },
-      #               {
-      #                 "type": "actions",
-      #                 "elements": [
-      #                   {
-      #                     "type": "button",
-      #                     "text": {
-      #                       "type": "plain_text",
-      #                       "text": "Failing Commit",
-      #                       "emoji": true
-      #                     },
-      #                     "url": "https://github.com/elastic/cloudbeat/commit/${{env.BREAKING_COMMIT}}"
-      #                   },
-      #                   {
-      #                     "type": "button",
-      #                     "text": {
-      #                       "type": "plain_text",
-      #                       "text": "Failed CI Run",
-      #                       "emoji": true
-      #                     },
-      #                     "url": "${{env.RUN_URL}}"
-      #                   }
-      #                 ]
-      #               }
-      #             ]
-      #           }
-      #         ]
-      #       }
+      - name: Slack Notification
+        uses: ./.github/actions/slack-notification
+        if: ${{ !cancelled() && failure() }} # Run only if the previous step failed
+        env:
+          BREAKING_COMMIT: "${{ github.event.workflow_run.head_sha }}"
+          RUN_URL: "${{ github.event.workflow_run.html_url }}"
+          RUN_NAME: "${{ github.event.workflow_run.name }}"
+          BRANCH: "${{ github.event.workflow_run.head_branch }}"
+          REPO: "${{ github.repository }}"
+        with:
+          vault-url: ${{ secrets.VAULT_ADDR }}
+          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
+          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
+          slack-payload: |
+            {
+              "text": ":alert: CI is failing on ${{ github.event.workflow_run.head_branch }} :alert:",
+            	"blocks": [
+                {
+                  "type": "header",
+                  "text": {
+                    "type": "plain_text",
+                    "text": ":alert: CI is failing on ${{ github.event.workflow_run.head_branch }} :alert:",
+                    "emoji": true
+                  }
+                }
+              ],
+              "attachments": [
+                {
+                  "color": "#D40E0D",
+                  "blocks": [
+                    {
+                      "type": "section",
+                      "text": {
+                        "type": "mrkdwn",
+                        "text": "Commit <https://github.com/elastic/cloudbeat/commit/${{env.BREAKING_COMMIT}}|${{env.BREAKING_COMMIT_SHORT}}> by ${{env.PR_AUTHOR}} has failing <${{env.RUN_URL}}|${{env.RUN_NAME}}> tests on the `${{env.BRANCH}}` branch."
+                      }
+                    },
+                    {
+                      "type": "divider"
+                    },
+                    {
+                      "type": "actions",
+                      "elements": [
+                        {
+                          "type": "button",
+                          "text": {
+                            "type": "plain_text",
+                            "text": "Failing Commit",
+                            "emoji": true
+                          },
+                          "url": "https://github.com/elastic/cloudbeat/commit/${{env.BREAKING_COMMIT}}"
+                        },
+                        {
+                          "type": "button",
+                          "text": {
+                            "type": "plain_text",
+                            "text": "Failed CI Run",
+                            "emoji": true
+                          },
+                          "url": "${{env.RUN_URL}}"
+                        }
+                      ]
+                    }
+                  ]
+                }
+              ]
+            }
